apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-poc-uzi
  namespace: argocd
spec:
  destination:
    namespace: uzi-space-dev
    server: https://kubernetes.default.svc
  project: default

  source:
   chart: uzi-helm-chart
   helm:
     values: |
       pushgateway:
         enabled: false
   repoURL: https://github.com/uzielferreira/CD-poc-uzi.git  
   targetRevision: HEAD       

#Source para argo sem helm
#  source:
#    path: Kubernetes
#    repoURL: https://github.com/uzielferreira/CD-poc-uzi.git
#    targetRevision: HEAD
  syncPolicy:   
 #   syncOptions:
 #     - CreateNameSpace=true
    automated:
      selfHeal: true
      prune: true