apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: site-poc-uzi
  namespace: argocd

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uzi-space
  project: default  
  source:
    repoURL: 'https://github.com/uzielferreira/CD-poc-uzi.git'
    path: uzi-helm-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - PruneLast=true