apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: poc-site-blu-green
    namespace: argocd
  spec:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: Kubernetes
      repoURL: https://github.com/uzielferreira/CD-poc-uzi.git
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
        selfHeal: true