apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: uzi-drone-runer-poc
  namespace: argocd

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uzi-space
  project: default  
  source:
    repoURL: 'https://github.com/uzielferreira/CD-poc-uzi.git'
    path: uzi-drone-helm/charts/drone-runner-kube
    targetRevision: HEAD
    helm:
#      releaseName: drone-runer    
      valueFiles:
        - values.yaml
  syncPolicy:   
    automated:
      selfHeal: true
      prune: true