apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: drone-poc-uzi
  namespace: argocd

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default  
  source:
    repoURL: 'https://github.com/uzielferreira/CD-poc-uzi.git'
    path: drone
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:   
    automated:
      selfHeal: true
      prune: true