apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: site-poc-uzi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uzi-space
  project: default  
  source:
    repoURL: 'https://github.com/uzielferreira/CD-poc-uzi.git'
    path: site-helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true